### ISSUE TITLE
打开 ttf 文件后程序闪退

### ISSUE THREAD

**Issue by zhiyiYo** [QQxiaoming/TTFviewer#12]
界面上的参数如图所示
![image](https://user-images.githubusercontent.com/65096819/217149127-625c1863-5b2a-43d8-a2bf-510eb4ffc1b5.png)

这是使用的 ttf 文件：
[SegoeMVRMDL2Assets.zip](https://github.com/QQxiaoming/TTFviewer/files/10671571/SegoeMVRMDL2Assets.zip)

歪个楼，界面上的 Width 拼写错了

**Comment by QQxiaoming** [comment]
感谢提问，我测试在Ubuntu上测试了一下你提供的文件结果如下：
![2023-02-07 13-47-57 的屏幕截图](https://user-images.githubusercontent.com/27486515/217159597-ac80c6ad-49d7-426a-a2e4-553426ea193d.png)
![2023-02-07 13-48-08 的屏幕截图](https://user-images.githubusercontent.com/27486515/217159612-5f0cc33b-3026-4031-9bc0-0ed6d8ca24ba.png)
看起来是正常的，但我没有windows是开发环境，也许确实存在问题，但我可能稍晚一点才能确认。

**Comment by QQxiaoming** [comment]
拼写确实存在问题，下个版本我会检查一下，感谢。

**Comment by QQxiaoming** [comment]
@zhiyiYo 你好，我借了同事的pc测试在v0.2.1版本的情况，并没有发生闪退的问题，因此目前不太清楚你那里发生问题。

**Comment by zhiyiYo** [comment]
好吧，辛苦了
